# Generated by Django 3.2.9 on 2021-11-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TinyUrl',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=1024)),
                ('counter', models.BigIntegerField()),
            ],
        ),
    ]
