# Generated by Django 3.2.9 on 2021-11-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinyurl',
            name='counter',
            field=models.BigIntegerField(default=0),
        ),
    ]
