# Generated by Django 3.2.9 on 2021-11-30 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tinyurl_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='TinyUrlRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tiny_id', models.CharField(max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
