# Generated by Django 3.2.9 on 2021-11-30 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_tinyurlrequest_tiny_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinyurlrequest',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 11, 30, 16, 11, 37, 406103)),
        ),
    ]
