# Generated by Django 3.2.9 on 2021-11-30 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_tinyurlrequest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinyurlrequest',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 11, 30, 16, 33, 17, 369992)),
        ),
        migrations.AlterField(
            model_name='tinyurlrequest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
