# Generated by Django 3.2.9 on 2021-11-30 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20211130_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinyurlrequest',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 11, 30, 16, 35, 19, 904226)),
        ),
        migrations.AlterField(
            model_name='tinyurlrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
