# Generated by Django 3.2.9 on 2021-11-30 15:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_tinyurlrequest_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinyurlrequest',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='tinyurlrequest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
