# Generated by Django 3.2.9 on 2021-11-30 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20211130_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tinyurlrequest',
            old_name='tiny_id',
            new_name='tiny_url',
        ),
    ]
