# Generated by Django 3.2.9 on 2021-11-30 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_tinyurlrequest_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tinyurl',
            name='counter',
        ),
    ]
